[build]
builder = "NIXPACKS"
buildCommand = "rm -rf node_modules package-lock.json && npm install && npm run build"

[deploy]
startCommand = "npm start -w api"
restartPolicy = "ON_FAILURE"
maxRetries = 3
